---

- name: Initiate PKI
  command: easyrsa --batch init-pki
  args:
    creates: "{{ easyrsa_pki_dir }}/private"
  when: not easyrsa_replace_pki | bool

- name: Replace PKI
  command: easyrsa init-pki
  when: easyrsa_replace_pki | bool
  changed_when: true

- name: Upload vars file
  template:
    src: vars.j2
    dest: "{{ easyrsa_pki_dir }}/vars"
    mode: 0o755

- name: Create CA
  command: >-
      easyrsa {{ '"--passin=file:' + (_easyrsa_tmpfile_capass | quote) + '"'
                                if   _easyrsa_capass_defined
                                else ''}}
              {{ '"--passout=file:' + (_easyrsa_tmpfile_capass | quote) + '"'
                                if   _easyrsa_capass_defined
                                else ''}}
              build-ca
              {{ '' if _easyrsa_capass_defined else 'nopass' }}
  register: _result
  failed_when:
    - _result is failed
    - _result.stderr | default(_result.stdout, true)
      is not search('you already seem to have one set up')
  changed_when: _result is not failed
