---
- name: Update cert password
  include_tasks: compute_certpass.yml

- name: Bundle certificates and keys into PKCS#12
  command: >-
    easyrsa
      {{ '--passin=pass:' + _easyrsa__cert_pass if _easyrsa__cert_pass_defined else '' }}
      {{ '--passout=pass:' + _easyrsa__cert_pass if _easyrsa__cert_pass_defined else '' }}
    export-p8 {{ _easyrsa__cert.name }}
  args:
    creates: "{{ easyrsa_pki_dir }}/private/{{ _easyrsa__cert.name }}.p12"
