---

- name: Bundle certificates and keys into PKCS#12
  include_tasks: convert_to_p12.yml
  when: _easyrsa__cert.pass | default(None)
  loop: "{{ easyrsa_to_pkcs12 }}"
  loop_control:
    loop_var: _easyrsa__cert
    label: "{{_easyrsa__cert.name}}"
  no_log: "{{ lookup('ansible.builtin.env', 'MOLECULE_FILE') is falsy }}"

- name: Convert private keys to PKCS#8
  include_tasks: convert_to_p1_p8.yml
  loop: "{{ easyrsa_to_pkcs8 }}"
  loop_control:
    loop_var: _easyrsa__cert
    label: "{{_easyrsa__cert.name}}"
  vars:
    _easyrsa_mode: p8
  no_log: "{{ lookup('ansible.builtin.env', 'MOLECULE_FILE') is falsy }}"

- name: Convert certificates to PKCS#7
  command: >-
    easyrsa export-p7 {{ item.name }}
  args:
    creates: "{{ easyrsa_pki_dir }}/issued/{{ item.name }}.p7b"
  loop: "{{ easyrsa_to_pkcs7 }}"

- name: Convert private keys to PKCS#1
  include_tasks: convert_to_p1_p8.yml
  loop: "{{ easyrsa_to_pkcs1 }}"
  loop_control:
    loop_var: _easyrsa__cert
    label: "{{_easyrsa__cert.name}}"
  vars:
    _easyrsa_mode: p1
  no_log: "{{ lookup('ansible.builtin.env', 'MOLECULE_FILE') is falsy }}"

