---
- name: Update cert pass file
  include_tasks: compute_certpass.yml

- name: Sign server certificates
  include_tasks: sign_cert.yml
  vars:
    _easyrsa_sign_mode: server
  loop: "{{ easyrsa_servers }}"
  loop_control:
    loop_var: _easyrsa__sign_cert
    label: "Server {{_easyrsa__sign_cert.name}}"

- name: Sign client certificates
  include_tasks: sign_cert.yml
  vars:
    _easyrsa_sign_mode: client
  loop: "{{ easyrsa_clients }}"
  loop_control:
    loop_var: _easyrsa__sign_cert
    label: "Server {{_easyrsa__sign_cert.name}}"
