#!/usr/bin/env python3

"""Generate defaults/main.yml from meta/argument_specs.yml.

Both defaults/main.yml and meta/argument_specs.yml hold default values for
variables. The latter, however, are not used by ansible to actually set the
default value of a variable, they are only meant as documentation. To avoid
maintaining two copies of the same defaults, this script will read the argument
specs and generate the defaults file based on that.
"""

from ruamel.yaml import YAML

defaults = {}

with open("./meta/argument_specs.yml") as f, \
    YAML(typ="rt") as yml:
    yml.preserve_quotes = True
    arg_specs = yml.load(f)

for name, spec in arg_specs.mlget(['argument_specs', 'main', 'options'], list_ok=True).items():
    if spec.get("required"):
        continue

    if spec.get("default") is None and spec.get("type") == "list":
        defaults[name] = []
        continue

    if spec.get("default") is None and spec.get("type") == "dict":
        defaults[name] = {}
        continue

    if spec.get("default") is None:
        continue

    defaults[name] = spec["default"]

with open("./defaults/main.yml", "w") as f, \
        YAML(typ="rt", output=f) as yml:
        f.writelines([
            "# Do not edit this file by hand\n",
            "# This file is auto-generated from meta/argument_specs.yml\n",
            "# using the meta/generate_defaults.py script.\n"
        ])
        yml.explicit_start=True
        yml.dump(defaults)
